theme: jekyll-theme-minimal
title: Digitial Acquisition of Big Data
description: <div id="#toc"/>
## Table of Contents
 [Day 1: Setting the Stage](#day-1) **|** [Day 2: JSON Data](#day-2) **|** [Day 3: XML Data](#day-3) **|**
[Day 4: The Rest of the Pipeline](#day-4) **|** [Day 5: Next Steps](#day-5) 

